### ISSUE TITLE
显示服务器玩家金钱排行榜

### ISSUE THREAD

**Issue by HongyiMC** [LiteLDev/LLEssentials#30]
### Describe the solution you'd like 您认为还缺少什么?

玩家输入 /money top 的时候显示服务器经济前十的玩家与他们的金钱数量

**Comment by Jaciezyt** [comment]
不要在LL主仓库发布插件相关问题
sa https://github.com/LiteLDev/LiteLoaderPlugins

**Comment by ShrBox** [comment]
5867a1ba82fa13b7115c663fbb950dc4ed18af8c
