### ISSUE TITLE
how to fix see the mountain range in front and then disappear?

### ISSUE THREAD

**Issue by powbie** [LiteLDev/LLEssentials#41]
![Ảnh chụp màn hình (176)](https://user-images.githubusercontent.com/123739742/215304660-a927d5e8-6d63-4569-b9b9-2d7a67940583.png)
''I have created server 1.19.51 and installed LLEssentials plugin for convenience tpa and set at home, but it usually shows a mountain of chunks in front of me and then disappears, although it doesn't affect the server as it's quite Discomfort with limited vision.''

**Comment by ShrBox** [comment]
https://docs.litebds.com/en/#/FAQ?id=client-chunk-error
